name: flutter_duration_picker
description: A widget for picking durations, inspired by Material Time Picker.
version: 2.0.0
author: Chris Harris <c@harrischris.com>
homepage: https://github.com/cdharris/flutter_duration_picker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter